### ISSUE TITLE
Embed.Length Evaluates to 0 If Any Operand Is Null

### ISSUE THREAD

**Issue by MarkKoz** [RogueException/Discord.Net#1011]
If any of the `Embed`'s properties which are operands in the calculation are `null`, the whole [expression](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Core/Entities/Messages/Embed.cs#L60) that is the left operand of the null-coalescing operator will evaluate to `null`. This causes the operator to return its right operand `0`. Note that the null-coalescing operator has lower precedence than the addition operator. 

Related [documentation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/using-nullable-types#operators):

> The predefined unary and binary operators and any user-defined operators that exist for value types may also be used by nullable types. **These operators produce a null value if the operands are null;** otherwise, the operator uses the contained value to calculate the result.

Probably among other things, I've noticed this has the consequence of `EmbedBuilder.Build()` not throwing `InvalidOperationException`.

Is this working as intended? Seems like an oversight to me.

**Comment by Still34** [comment]
This isn't quite correct. If you add `null` with an `int`, the compiler will make it an `int?`. However, there is still one oversight; since `Fields.Sum(f => f.Name.Length + f.Value.ToString().Length)` does its calculation without the safe operator, `Fields.Sum` will return an `int` and will throw if there are no field name/value.

**Comment by Still34** [comment]
This should be resolved in 2988b38.
