### ISSUE TITLE
JSON Parsing: Circular reference in `SocketGuildUser`

### ISSUE THREAD

**Issue by 2Kreeper** [RogueException/Discord.Net#1066]
When trying to serialize an event result (in this particular case `DiscordSocketClient.ChannelCreated` and `DiscordSocketClient.MessageReceived`) to JSON using [Json.NET](https://www.newtonsoft.com/json), an exception is thrown: `JsonSerializationException: Self referencing loop detected for property 'Owner' with type 'Discord.WebSocket.SocketGuildUser'`.
This is a serious problem as it makes logging of any type impossible!

**Comment by AntiTcb** [comment]
A good rule of thumb to follow is not to serialize someone else's classes. Aside from the models used for interacting directly with Discord's API, none of the classes in this lib are designed to be serialized.

It's not a problem, and no, logging is not impossible. You should be creating a separate model that you serialize the data you need with, rather than serializing a `SocketGuildUser` instance directly. You could even most likely get away with only storing the user's ID, and then using that ID to retrieve their `SocketGuildUser` object instance from the client.

**Comment by FiniteReality** [comment]
As said above, this is not an issue. Create your own classes which you can serialize; our public types are not intended to be serialized.
