### ISSUE TITLE
'explicit_content_filter' is not available in Guild commons?

### ISSUE THREAD

**Issue by Kein** [RogueException/Discord.Net#1113]
Speaking of this:  
https://discordapp.com/developers/docs/resources/guild#guild-object-explicit-content-filter-level

**Comment by Still34** [comment]
One of the to-dos. Several of our models are outdated, and this is one of them. There are other outdated models such as the message model where it's missing the `activity` prop and such.

**Comment by Chris-Johnston** [comment]
I've got a PR ready to fix this change, but I'm going to be greedy and wait until Hacktoberfest begins (a few days from now) to create it. Could I claim this issue please?

https://github.com/Chris-Johnston/Discord.Net/tree/implement-explicit-content-filter

Also, regarding models being out of date, `Guild.cs` is also missing `application_id`, `widget_enabled?`, and `widget_channel_id?`.

Update: Turns out `widget` appears to have the same values as the `embed` properties. Two names for the same thing?
