### ISSUE TITLE
Sending message along with uploaded file

### ISSUE THREAD

**Issue by sponge** [RogueException/Discord.Net#118]
The Discord API supports attaching a message to uploaded media, but Discord.net doesn't expose it. As far as I can tell, there is just a "content" parameter that needs to be sent along with the request. https://discordapp.com/developers/docs/resources/channel#upload-file

Is there any chance at getting this updated (or any workaround that can be done in the current version)?

**Comment by RogueException** [comment]
Support for this has been added to 1.0-dev already, but we probably won't be backporting to 0.9.x.

0.9's rest client wasn't designed with additional parameters in mind, since Discord added this to upload-file after 0.9's release. There's no easy workaround really short of manually creating the request yourself.

**Comment by khionu** [comment]
It's not hard to do, mind you. Just look at the internal requests, and make a new class based off of them, send it via `await Client.ClientAPI.Send()`

**Comment by RogueException** [comment]
The uploadfile request is special though since it's a multipart instead of json, not so simple @khionu
