### ISSUE TITLE
 No type reader found for type IAudioClient, one must be specified 

### ISSUE THREAD

**Issue by UltWolf** [RogueException/Discord.Net#1229]
Good day.
Sorry for disturbing you, i do all what you was wrote in guide :
https://discord.foxbot.me/stable/guides/voice/sending-voice.html
For example:
In by bin\Debug\netcoreapp2.1 folder  i have:
dll from Opus,libsodium, and from FFPMEG:
https://ffmpeg.zeranoe.com/builds/
I have version 4.1 , Windows 64bix, shared libr.
I was wrote all what you recomend in your`s guides, where i did mistakes?
Href of repo:
https://github.com/UltWolf/Bots/tree/master/Music%20discord%20bot

**Comment by UltWolf** [comment]
Screenshot of my debug folder 
![default](https://user-images.githubusercontent.com/18503527/50632682-68692680-0f51-11e9-9e0f-0414c74ed9f7.png)

**Comment by Joe4evr** [comment]
As your error states, there is no type reader for types that implement `IAudioClient`, so you can't use this type as a command parameter.

The bigger issue is that you *shouldn't* require commands to take a client as a parameter (since it's impossible for users to specify one anyway), but rather keep track of those yourself by using a dictionary, [like how this example is laid out](https://gist.github.com/Joe4evr/773d3ce6cc10dbea6924d59bbfa3c62a#file-audioservice-cs-L10).

**Comment by UltWolf** [comment]
Yeah, thanks very much, it`s working . ^_^ FInally
