### ISSUE TITLE
NullReferenceException occurs when attempting to DM a `RestUser` retrieved from `DiscordSocketClient.Rest`

### ISSUE THREAD

**Issue by adamgauthier** [RogueException/Discord.Net#1277]
### Steps to reproduce
1. Create a simple `DiscordShardedClient`, login and start it.
2. In ready, use the `DiscordSocketRestClient` exposed by `DiscordSocketClient.Rest` to retrieve an existing `RestUser`.
3. Notice the user is fetched correctly.
4. Use `UserExtensions#SendMessageAsync` extension method to send a DM to the user.
5. Notice a `System.NullReferenceException` is thrown from the library.

### Expected Result
A message is correctly sent to the retrieved user.

### Code Example
```csharp
public async Task ShardReadyAsync(DiscordSocketClient shardClient)
{
    // Use existing user id
    var restUser = await shardClient.Rest.GetUserAsync(0);
    await restUser.SendMessageAsync("A Message");
}
```

### Exception Thrown
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.Rest.RestDMChannel..ctor(BaseDiscordClient discord, UInt64 id, UInt64 recipientId)
   at Discord.Rest.RestDMChannel.Create(BaseDiscordClient discord, Channel model)
   at Discord.Rest.UserHelper.CreateDMChannelAsync(IUser user, BaseDiscordClient client, RequestOptions options)
   at Discord.Rest.RestUser.Discord.IUser.GetOrCreateDMChannelAsync(RequestOptions options)
   at Discord.UserExtensions.SendMessageAsync(IUser user, String text, Boolean isTTS, Embed embed, RequestOptions options)
```

### Further Details
Exception occurs because `discord.CurrentUser` is `null`.
```csharp
internal RestDMChannel(BaseDiscordClient discord, ulong id, ulong recipientId)
            : base(discord, id)
        {
            Recipient = new RestUser(Discord, recipientId);
            CurrentUser = new RestUser(Discord, discord.CurrentUser.Id);
        }
```

**Comment by k-boyle** [comment]
Did some digging and the issue is because of `DiscordSocketRestClient`'s `CurrentUser` prop never gets set since the client doesn't log in, I tried to come up with an idea on how to fix this but I couldn't think of something that wasn't a duct tape implementation. 

My current solution was to mark the login and logout methods on the client as internal and hide them. Then in the `DiscordSocketClient`'s `OnLoginAsync` and `OnLogoutAsync` call the login and logout method of the rest client
