### ISSUE TITLE
System.InvalidOperationException when reading SocketMessage.Attachments

### ISSUE THREAD

**Issue by InfinityGhost** [RogueException/Discord.Net#1291]
Occasionally on certain messages, attempting to read the `SocketMessage.Attachments` property throws a `System.InvalidOperationException`

>This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.

**Comment by Joe4evr** [comment]
Looks like this is caused by us [not initializing the field for the property override in SocketUserMessage](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Entities/Messages/SocketUserMessage.cs).

~~While we're at it, I noticed that in SocketMessage, we're using `ImmutableArray.Create<T>()`, which possibly allocates an empty array every time? We should just use the `ImmutableArray<T>.Empty` field instead, to reduce complexity.~~ EDIT: [Looks like `Create<T>()` calls the field itself](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs#L28), but I'd still advocate for using the field anyway since that wouldn't be dependent on JIT inlining to get the same perf.
