### ISSUE TITLE
Question about entity design

### ISSUE THREAD

**Issue by reflectronic** [RogueException/Discord.Net#1341]
Hello,

I see that you have primarily bifurcated the implementations of entities into `Rest*` and `Socket*` variants — however, I can't really see why that was done; what actually ends up being the difference between the two? Isn't there only one schema for the data that comes back from Discord's API? For example — to my knowledge, it's not possible to interact with messages over WebSocket (the only message APIs operate on REST); why is there a `SocketMessage` type then & how is it different than `RestMessage`?

Thanks!

**Comment by Still34** [comment]
I believe the design inconsistencies will be addressed in the upcoming v3 currently being discussed in #1249.

**Comment by AntiTcb** [comment]
> Hello,
> 
> I see that you have primarily bifurcated the implementations of entities into `Rest*` and `Socket*` variants — however, I can't really see why that was done; what actually ends up being the difference between the two? Isn't there only one schema for the data that comes back from Discord's API? For example — to my knowledge, it's not possible to interact with messages over WebSocket (the only message APIs operate on REST); why is there a `SocketMessage` type then & how is it different than `RestMessage`?
> 
> Thanks!

From Discord's end, yes, there is only one schema, however, each protocol technically has its own sub-schema. Some properties are exclusive to a protocol. Example being, every property with an asterisk on the [Guild object](https://discordapp.com/developers/docs/resources/guild#guild-object-guild-structure) is only ever present when received through the READY payload from the websocket. 

The splitting of the entities comes from:
* The design idea to be able to have individual protocols of the API split into their own separate projects & NuGet packages, so that if you only wanted to work with REST, you didn't need to include the WebSocket portions of the library as well.
* Being that C# is strongly typed, the separated entities would then not expose properties/methods that were only present depending on the protocol, and just leaving them as null properties otherwise. It would be a little cumbersome to have to have `Guild#MemberCount` declared as an `int?` when it's only ever null through REST and always an `int` through WebSocket, so, it made a little more sense to just not have the property at all on the REST entity.
