### ISSUE TITLE
IAudioClient.StreamCreated is not called

### ISSUE THREAD

**Issue by jnccd** [RogueException/Discord.Net#1395]
```
Console.WriteLine("Action was called");

IAudioClient client = await channel.ConnectAsync();
client.StreamCreated += async (ulong id, AudioInStream stream) => {
  Console.WriteLine("StreamCreated was called");
  await Task.Delay(recordingTime);
  await channel.DisconnectAsync();
  stream.CopyTo(mem);
  doneListening = true;
};
```

Executing this code results in the following Console Output:

```
Action was called
14:03:50 Audio #1    Connecting
14:03:50 Audio #1    Unknown OpCode (Hello)
14:03:51 Audio #1    Connected
```

So StreamCreated was never called. 
Is receiving audio currently not supported? 
I couldn't find any example code for this use case.

**Comment by k-boyle** [comment]
Discord enforces a limitation that you have to send audio before you can receive it

**Comment by jnccd** [comment]
@TheCasino Okay I updated the code
```
Console.WriteLine("Action was called");

IAudioClient client = await channel.ConnectAsync();
client.StreamCreated += async (ulong id, AudioInStream stream) => {
  Console.WriteLine("StreamCreated was called");
  await Task.Delay(recordingTime);
  await channel.DisconnectAsync();
  stream.CopyTo(mem);
  doneListening = true;
};

using (WaveStream naudioStream = WaveFormatConversionStream.CreatePcmStream(
  new StreamMediaFoundationReader(
    new FileStream("Commands\\Edit\\StartListeningSoundEffect.mp3", FileMode.Open))))
  await MultiMediaHelper.SendAudioAsync(client, naudioStream);
```
But this still results in the same Console Output
Edit: In case you think its because the audio sending doesn't work, I'm literally in the voice channel and hear it.

**Comment by cmorley191** [comment]
Aside from the issue of sending audio once in order to receive audio, there is another issue preventing StreamCreated from being called.

You will notice that StreamCreated _does_ get called if, during the recording part of your code, a new user joins the voice channel (a stream gets created for this user). (you can also do this by you, the user, leaving the voice channel and rejoining after the bot has joined).

I conclude that StreamCreated _is_ getting called, but it's getting called before ConnectAsync() returns - StreamCreated is called by an internal method of the API triggered by the VOICE_STATE_UPDATED message being received from the discord api. This message is received _before_ the channel finishes ConnectAsync(); that is, before you ever have access to the IAudioClient in order to add a StreamCreated event handler.

This is an oversight/bug of Discord.Net. There is currently no way to gain access to the AudioInStreams of users that were already connected to the voice channel that your bot joins, because there's no way to add a StreamCreated event handler before these users' streams are created (since ConnectAsync has not yet completed, and these users' streams are created during ConnectAsync). You can only get access to AudioInStreams once users join the channel after your bot joins.

**Comment by cmorley191** [comment]
I definitely plan on helping to come up with changes that can be made to Discord.Net to get around this issue, but I would appreciate if someone experienced with this project can first confirm my conclusions.

**Comment by cmorley191** [comment]
Two potential fixes to this issue... (giving the API user access to the streams of the discord users that were already connected to the voice channel when the API connected)

**1. Make the AudioClient's dictionary of streams (<ulong, AudioInStream>) publicly accessible in some way.**
This solution may only lead to more confusion for the API users, as most users would then probably do something like this:
```
private async Task HandleStreamCreated(ulong id, AudioInStream stream) { ... }

IAudioClient client = await channel.ConnectAsync();
client.StreamCreated += HandleStreamCreated;
foreach (var pair in client.Streams) {   // access the client's dictionary of streams to handle the initial connections
    HandleStreamCreated(id: pair.Key, stream: pair.Value);
}
```
There's a potential race condition here - if a stream is created between the line where the event handler is added and the start of the for loop, the handler will be called twice for that stream.

Therefore, I prefer the second solution: (despite it being a little heavier)
**2. Instead of ConnectAsync returning an AudioClient, each SocketGuild should expose a public, readonly AudioClient which is initially not connected to any channel.** Then API users can add an event handler before connecting to the channel, and the event handler will be called for all the initial discord users' streams.
```
private async Task HandleStreamCreated(ulong id, AudioInStream stream) { ... }

channel.Guild.AudioClient.StreamCreated += HandleStreamCreated;  // access the guild's public AudioClient instance
await channel.ConnectAsync();  // ConnectAsync now returns nothing (just Task)
// to access the audio client again, just use channel.Guild.AudioClient
```
The drawback to this approach is that ConnectAsync should likely just return `Task`, rather than `Task<IAudioClient>`. This would break the code of existing users that use the returned audio client of ConnectAsync. (and break the example in the Discord.Net docs' intro page)

Comments on these solutions are appreciated (before I attempt to implement the second one).

**Comment by martindevans** [comment]
As a third option, how about an additional optional parameter in `ConnectAsync` which is a function that runs after the object is created, but before any events are processed? Something like this:

    using var c = await Channel.ConnectAsync(false, false, false, c => {
        c.StreamCreated += async (userId, stream) => {
            // Hello :D
        };
        c.StreamDestroyed += async userId => {
            // Goodbye :(
        };
    });

This way, the event handlers are not subscribed too late and most existing code using these events will be very easy to migrate. It's also not a breaking change to any code (as the event handlers would still exist).

Edit: I will be happy to implement this and submit a PR, if this approach is ok?
