### ISSUE TITLE
Multiple user activities possible?

### ISSUE THREAD

**Issue by Xathz** [RogueException/Discord.Net#1428]
If the user has a custom status set you can not get any other activity data (Spotify, rich, etc).

Not sure if this is a restriction of the Discord api only giving a single activity, I couldn't find any exact info.

Version: `Discord.Net v2.2.0-dev-20191130.5`

https://github.com/discord-net/Discord.Net/blob/a4846516fbce6cc3f80c04be43667f34048e23c4/src/Discord.Net.WebSocket/Extensions/EntityExtensions.cs#L10

**Comment by ndelta0** [comment]
I can't see anything about multiple rich presences in Discord's API documentation, it's not possible to have more than one presence.

**Comment by D-Kay6** [comment]
It's not about having multiple presences.
The problem is that since custom statuses have been added to discord, you can no longer get the game a user is playing from their activity if they have a custom status.

Previously you could just get the activity name, which would be the name of the game.
Now, if the user has a custom status, that name is the text of the custom status.

**Comment by ndelta0** [comment]
Well, since both are rich presences it works like that. I think the order in which they show up (1 being highest priority)

1. User's custom presence
2. Game/Application rich presence (like League of Legends or Visual Studio Discord RPC Extension)
3. Listening to Spotify
4. Playing **game** (no rich presence, just game name), watching **something**, etc.

And being online, idle, DnD, offline
It's true, it makes reading the game status hard, but there's probably nothing you can do about it.

**Comment by LoudSoftware** [comment]
I've been running in a similar issue while trying to port one of my bots from discord.js to discord.net however I am observing a different priority order:
1. Cusom presence
2. Spotify
3. Game/Application rich presence (Visual studio Discord RPC extension)
4. Playing game

Which is very annoying because the aim of the bot is to monitor the game or RPC you're currently on except spotify, in order to dynamically rename the voice channel you're currently in to reflect the game or app most connected users are currently playing/using.

This becomes way less accurate as soon as anyone is listening to spotify as then there's no way to know if they are just listening to spotify or doing so while playing a game or using a discord rich presence compatible software.
