### ISSUE TITLE
Server requested a reconnect

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1479]
The socket client should correctly reconnect and resume after the "[Server requested a reconnect](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/DiscordSocketClient.cs#L514)" exception is thrown (which is about every 20-40 minutes.)

Ref: [b1nzy's words](https://discordapp.com/channels/81384788765712384/381871767846780928/695380999063863406)

**Comment by Anu6is** [comment]
Those aren't related issues

**Comment by RheaAyase** [comment]
Yes they are, you can't handle this and correctly reconnect without first being able to - without the client hanging etc.

**Comment by RheaAyase** [comment]
I mean sure you can write the code, but it won't work right...

**Comment by renanrcp** [comment]
Those aren't related issues².

https://github.com/discord-net/Discord.Net/issues/1448 The first issue is a Dispose/Close connection problem.

https://github.com/discord-net/Discord.Net/issues/960 The second issue is a start connection problem, you can see the error: "Server missed last heartbeat"

**Comment by RheaAyase** [comment]
#960 is generic "can't reconnect" issue and it's irrelevant of the source of the problem. Not only server missed last heartbeat, but also websocket disconnects, etc. There isn't a single situation in which it can reconnect successfully at all.

And by that logic, no matter what we do in this issue, it's not gonna work until 960 is resolved.

**Comment by JOBBIN9422** [comment]
I am also running into this issue - reconnect requests being sent around once per hour or so. Server reconnect requests disconnect the audio client from the current channel if it's connected. Here's a screenshot of the console output for reference.
![heartbeat](https://user-images.githubusercontent.com/32369412/79226829-9e6baa80-7e24-11ea-9c12-cd1cb0418280.PNG)

**Comment by JOBBIN9422** [comment]
Here's a more typical example of the reconnect requests when the bot is idle:
![image](https://user-images.githubusercontent.com/32369412/79229111-1f787100-7e28-11ea-82b5-4ca673de04b5.png)

**Comment by pengowray** [comment]
via Jake#0001 (Discord Staff) on the "Discord API" discord: [~April 3]

> Discord is rolling out a software update to our gateways.  We anticipate no issues, and have had a canary of the new code running for a while now with no issue. This update introduces only one user visible change.
> 
> Your gateway connection will regularly be asked to reconnect using opcode: https://discordapp.com/developers/docs/topics/gateway#reconnect
> 
> You can simply reconnect and resume as you would tolerate the gateway connection being interrupted via other causes. We are doing this to allow for organic rebalancing of long-lived connections between nodes as nodes eventually start to auto-scale in/out

Via above documentation link:

> **Reconnect**
>The reconnect event is dispatched when a client should reconnect to the gateway (and resume their existing session, if they have one). This event usually occurs during deploys to migrate sessions gracefully off old hosts.

**Comment by pengowray** [comment]
Is anyone working on this? I have a bot serving 3.8k discords which is barely functional half the time since these changes, as it takes so long for it to come back online and reconnect its shards. I can't tell if the people working on this project even realise there's a problem. I don't know what to tell my users. Is anyone working on it?

**edit:** Seems my problem was just that I was running out of RAM. Memory usage spikes a lot during a reconnect, thus why the regular reconnections seemed to impact me more than others. Each reconnect would cause the bot to crash over and over again while it fought with the garbage collection until enough RAM was free to start back up.

I'm guessing all the guild & user data structures are recreated each reconnect.

**Comment by ExtraJuiceMan** [comment]
I was pulling out my hair over this the other day because my bot kept getting forced token resets from identifying on the websocket and did some research. It turns out that if you close the websocket with code 1000 (which Discord.Net does), Discord will invalidate the session and the client will be unable to resume. discord.py had this issue and fixed it by closing the websocket with code 4000 instead.

https://github.com/Rapptz/discord.py/commit/403651a1440260cb46f42d68a82ee35e193a350d

**Comment by FiniteReality** [comment]
>  It turns out that if you close the websocket with code 1000 (which Discord.Net does), Discord will invalidate the session and the client will be unable to resume. discord.py had this issue and fixed it by closing the websocket with code 4000 instead.

If I could pin comments, this would absolutely be pinned.

**Comment by FiniteReality** [comment]
As mentioned in #1500, I haven't tested the fix extensively, so if somebody could check out those changes and try it in one of their bots, that would be excellent.

**Comment by JOBBIN9422** [comment]
I have checked out the changes and am running them on my bot at the moment. I will post an update once I receive a reconnect request! Btw - thank you for working on this!

**Comment by JOBBIN9422** [comment]
This was the output from the last reconnect request I received after running the bot with the fix applied:
**EDIT:** disregard this, was not running bot with the relevant fix applied.
![image](https://user-images.githubusercontent.com/32369412/80250620-d4393c00-8639-11ea-84a9-1ce77d33dbbc.png)

**Comment by FiniteReality** [comment]
You're not running with the fix @JOBBIN9422 - the exception with the message `Server requested a reconnect` should be a `GatewayReconnectException`. (https://github.com/discord-net/Discord.Net/blob/feature/disconnect-with-code/src/Discord.Net.WebSocket/DiscordSocketClient.cs#L514)

**Comment by JOBBIN9422** [comment]
Oh, sorry about that! I cloned from `dev` instead of the branch with your fix. Disregard that!
