### ISSUE TITLE
Impossible to overwrite default type reader for type that implements IMessage, IChannel, IRole or IUser

### ISSUE THREAD

**Issue by adamgauthier** [RogueException/Discord.Net#1485]
### Steps to reproduce
1. Create and register a type reader for `IMessageChannel` that simply returns the current channel regardless of input.
2. Add a command that uses a parameter of type `IMessageChannel`.
3. Start the client and attempt to use the command with gibberish input.
4. Notice the default type reader for `IChannel` is used and the command does not have the current channel as the parameter.

### Expected Result
It is possible to overwrite the default type reader for types that implement the entity types `IMessage`, `IChannel`, `IRole` and `IUser`.

### Code Snippet
```csharp
// Custom Type Reader
public class MessageChannel : TypeReader
{
    public override Task<TypeReaderResult> ReadAsync(ICommandContext context, string input, IServiceProvider services)
    {
        return Task.FromResult(TypeReaderResult.FromSuccess(context.Channel));
    }
}

// CommandService configuration
commandService.AddTypeReader<IMessageChannel>(new MessageChannel(), replaceDefault: true);

// Command
[Command("channelid")]
public Task ChannelIdAsync(IMessageChannel channel)
{
    return ReplyAsync(channel.Id.ToString());
}
```

### Additional Information
- Tested with version `2.3.0-dev-20200417.1`.
- It is possible to overwrite default type readers for entity types (`IMessage`, `IChannel`, `IRole` or `IUser`) directly, but not types that implement them (`IMessageChannel`, `IGuildUser`, ...). 
- Issue was introduced with #1083.

**Comment by SubZero0** [comment]
I remember this being discussed before and if I record correctly, the issue is how type readers are prioritized and separated. It being: default type readers > entity type readers > custom (added by user) type readers, each one having their own list.

Previously it wasn't possible to replace the default ones because of a change, see #1009 .
Now it is possible but incomplete because of how entity type readers are handled.

Imo, giving a higher priority to type readers added by the user is the correct way (+ checking if its an entity type reader), but it needs to be redone because of a previous issue, #941 .
