### ISSUE TITLE
IAsyncEnumerable could not be found

### ISSUE THREAD

**Issue by Nihlus** [RogueException/Discord.Net#1508]
Discord.Net.Core has an explicit reference to System.Interactive.Async 4.0.0, which no longer explicitly defines IAsyncEnumerable<T> - instead, it forwards to Microsoft.Bcl.AsyncInterfaces. Having an explicit reference like this breaks compilation for .NET Core 3+ and C#8 projects.

I'm not certain what the specific set of parameters that cause the error are, as IAsyncEnumerable has proven to be very tricky to use in the .NET Core ecosystem. However, there are other people experiencing this issue around the internet.

https://stackoverflow.com/questions/58247295/how-to-fix-reference-to-type-iasyncenumerable-claims-it-is-defined-in-syst

Either downgrading to System.Interactive.Async 3.1.1 or removing the reference altogether seems to work around the issue.

----
Discord.Net: 2.2.0
netcoreapp3.1/netstandard2.1
C#8

**Comment by Hawxy** [comment]
> Having an explicit reference like this breaks compilation for .NET Core 3+ and C#8 projects.

Well, no. It correctly forwards the types. The issue mentioned in the referenced StackOverflow post was fixed by updating this library to lx.net 4.0.0+, which was released in 2.2.0. I run two bots on .NET Core 3.1 with C#8 and they're working fine. 

If you're still seeing problems, it's because you either have an old version of discord.net installed, or some other package you take a dependency on references lx 3.1.1 and hasn't been rebuilt against 4.0.0 (ie EFCore 2.1 is incompatible).

**Comment by Nihlus** [comment]
I don't see where I could have a reference to System.Interactive.Async version other than 4.0.0 anywhere in my project tree. Downgrading Discord.NET to 2.1.1 from 2.2.0 resolves the issue - the only thing that changes between a working and a nonworking setup is the Discord.NET version referenced by my project.

**Comment by Hawxy** [comment]
I took a look at your bot and was able to reproduce the issue. The same functions definitely work fine in a clean .NET Core 3.1 project, so this might be an edge-case uncovered by your bot's structure, build pipeline or dependency tree. I'll continue to investigate when I have some spare time.

**Comment by GIRU-GIRU** [comment]
i'm having this issue after updating to the nightly builds with seymour

Could not load type 'System.Collections.Generic.IAsyncEnumerable`1' from assembly 'System.Interactive.Async, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.

tried referencing 'System.Interactive.Async, to no avail

**Comment by Hawxy** [comment]
> Could not load type 'System.Collections.Generic.IAsyncEnumerable`1' from assembly 'System.Interactive.Async, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.

This isn't the same issue. From looking at your repo, I'm guessing this is a runtime exception that happens when something reads from your database via Entity Framework. Update your EF version to fix it, EF 2.x is not compatible with lx.NET 4.x.

**Comment by GIRU-GIRU** [comment]
you are correct, thanks very much

**Comment by Hawxy** [comment]
@Nihlus As far as I can tell, your issue is that you have `Discord.Net.Commands` and `Discord.Net.Core` explicitly referenced in DIGOS but not `Discord.Net.Websocket` (which includes `.Rest`). I'm guessing you tried to update the two packages and encountered the compiler error in `Plugins.Roleplaying` due to `Discord.Net.WebSocket 2.1.1` being resolved via `Remora.Discord.Behaviours` a couple of layers down. Simply adding `Discord.Net.WebSocket` to `Plugins.Roleplaying` fixes the compiler error and everything builds fine. 

If you end up hitting a runtime exception around `Remora.Discord.Behaviours`, add a NS2.1 target to it and recompile it against the latest release of Discord.NET

As a side note, `DIGOS.Ambassador.Plugins.Abstractions.Database` is missing from the solution, and Stylecop should be put out of its miserable existence.

**Comment by Nihlus** [comment]
I'll try that, thanks! Why is it that I need to explicitly reference the websocket package when commands implicitly carries that reference? I'm trying to keep the dependencies in the projects as slimmed and low in the chains as possible.

The database abstractions are removed, yeah - I'm not sure why they're still being referenced. I'll have to have a look at that. 

As for StyleCop, it keeps my code consistent and clean when new contributors come in, and saves me a lot of time in review ;)

**Comment by Joe4evr** [comment]
> Why is it that I need to explicitly reference the websocket package when commands implicitly carries that reference?

Commands doesn't reference the WebSocket package, only the Core package.
https://github.com/discord-net/Discord.Net/blob/0c16d2f538a7cb9a683800014881dc60ec34dbb3/src/Discord.Net.Commands/Discord.Net.Commands.csproj#L10-L12

**Comment by Nihlus** [comment]
In that case, why do I need to add that reference at all? Just a version mismatch from the Remora dependency, so I get the newer one?

If that's the case, that explains it :) IAsyncEnumerable is such a damn pain to use sometimes.

**Comment by Nihlus** [comment]
Yeah, that was it. Upgrading the packages in Remora solved the issue.
