### ISSUE TITLE
Discord user is NULL

### ISSUE THREAD

**Issue by panthernet** [RogueException/Discord.Net#1533]
Got some weird issues after the update to the latest lib version. I read user command from chat to proceed with authentication, get the author ID and then try to get `SocketGuildUser` using the `SocketGuild.GetUser(ID)` but it returns NULL. User is in the guild, transition from command to processing logic is less than a second. The problem is that the issue is floating, sometimes it works just fine.

- I call `await discordGuild.DownloadUsersAsync();` before the processing to make sure the cache is up to date.
- I have one guild with strict ID specified
- I have this one guild cached in a variable at startup (can be a problem here?)
- Guild `IsConnected` and `HasAllMembers` properties are `True`. Restart do not solve it.

Please help me to get a clue on what is going on and how i can solve it.

PS: seems like users cache leaves old users after I purge them from discord and call `DownloadUsersAsync`, it shows 990 users against 737 in discord. After bot restart it shows correct 737 but the issue still remains.
PS2: When I've added extended logging and restarted the bot one more time, it passed the check :E Will wait for another issue. Can't reproduce with my alt reg.

**Comment by panthernet** [comment]
Done some more tests, looks like it happens for users who just showed up on server. The `DownloadUsersAsync` don't add them into cache. There's no such user in `Guild.Users` list. I see that `DownloadUsersAsync` don't wait for execution but still I have the same result for several hours when the background task has been completed.

**Comment by AraHaan** [comment]
I never ran into this issue, then again I never download the users either and just manually check using api requests if there are users (from this library ofc) Maybe you could hook into the on_user_join and on_user_leave events to then redownload them right when they join / leave the server?

**Comment by panthernet** [comment]
I will try to play with these events but results are troubling me. The guild is perfectly fine but the method returns NULL when I try to fetch user which is clearly present in Discord guild. The guild Users list do not have this new user even after `DownloadUsersAsync` is finished running.

Maybe I'll downgrade the lib version to see if anything changes.

**Comment by Xathz** [comment]
Having the same issue. New users that join the guild are never put into the cache after updating to v2.2.0. Works fine in v2.1.1 and earlier. Tried to downgrade and it works again.

If this helps the guild has ~23k members

**Comment by AraHaan** [comment]
This is interesting.

**Comment by panthernet** [comment]
Mine has around 1k people. Desperately lack time to provide more testing, sorry but the issue persists.

**Comment by SubZero0** [comment]
I couldn't reproduce this issue.

My test was tracking the Join and Leave in the Discord API guild (~58k), and, after someone joined, I would download all users. I left it running for 5 hours.

It always had the correct amount, were added/removed correctly, and had the expected results.

Log: [https://hastebin.com/fazowemune.sql](https://hastebin.com/fazowemune.sql)

I would suggest providing at least logs of what's happening, debugging the library by yourself would be even better.

**Comment by panthernet** [comment]
Okay, I'd tired of this issue and tried to debug it using the library code at hand. This decision leaded me to the interesting conclusion. I don't get this issue with the library code (latest) compiled from the projects inside my solution. In the same time the issue persists for library installed from NuGet both 2.2 and 2.1 versions. 

Weird but true.

**Comment by panthernet** [comment]
I can't track the source of the problem though. I call `SocketGuild.GetUser()` method which is a very simple wrapper around the fetch from `ConcurrentDictionary` of `SocketUsers` and it returns me NULL.

**Comment by panthernet** [comment]
Would be nice to hear some feedback for the issue as I can't use NuGet version currently to deploy cloud-based builds. Thank you.

**Comment by SubZero0** [comment]
If you can't provide a way to reproduce it, it will mostly depend on you finding where the issue is (or what possibly could be causing it). Otherwise, other people (like me) would need to take blind shots since we can't repro it.

If the nightly works, you probably just need to wait until the next version goes to NuGet.

**Comment by panthernet** [comment]
@SubZero0 I see, if only I could reproduce it either :) Only getting it on production platform. Will wait for the next release *sigh*

**Comment by RheaAyase** [comment]
This is not an easy one to reproduce, but it happens very often (and has been for years) seemingly randomly. People join a guild and GetUser returns null, even when these people actively speak in the chat and the bot reads their messages. `guild.DownloadUsers` doesn't solve this problem, like @panthernet mentioned.

From looking at what updates it, I think that this has something to do with `guild.IsSynced` since that seems to skip updating the "list" on message received, if it's false. Which would imply that the DownloadUsersAsync didn't work right which was triggered on GuildAvailable (and also why any subsequent calls do not fix anything.)

**Comment by RheaAyase** [comment]
Also it's kinda sad that GetUser (or `GetUserAsync => GetUser` uh huh) simply does `if(hasCache) return cache; else NULL;` instead of `if(hasCache) return cache; else fetch;` with the CacheMode to optionally allow such fetching like we can see elsewhere

Too much weight on that isSync'd promise thing.

**Comment by radiant-alex** [comment]
Hi, faced with the same issue. Bot is not bound to any server, and I try to get an instance of User by calling GetUser(ID), which always return null.
Please advise, how can I send DM to a particular user either by its ID or name?

**Comment by cuppyzh** [comment]
@radiant-alex [this](https://stackoverflow.com/questions/43942006/discord-net-sending-direct-messagepm-to-specified-user) might help you

**Comment by radiant-alex** [comment]
Thank you, but that does not help. I am still getting NULL from GetUser  :(
Perhaps something is wrong with permissions? For Scopes I've got "bot" only, for Permissions - "Send Messages"  (2048).

**Comment by stewieoO** [comment]
I also have this issue. 
I have a server with only 2 users + the bot.
`AlwaysDownloadUsers` is set to true and i explicitly trigger the DownloadUsersAsync() in the GuildAvailable event.

It seems that the list is never actually downloaded because it never calls the `GuildMembersDownloaded` event.

**Comment by 230Daniel** [comment]
Just in case anybody hasn't sussed this out, the GetUser(id) method only interacts with the client's cache. If you're having issues with the cache and need to get someone by ID, use GetUserAsync(id) which directly queries Discord's REST API.

I found that on the nightly builds, neither `AlwaysDownloadUsers = true` nor `SocketGuild.DownloadUsersAsync()` work, despite having the GuildMembers and Guild intents enabled. They don't throw an error, they just get stuck.

If I enable the presence intents, AlwaysDownloadUsers works again. I don't see why presence data should be required to get the members of the server, so I'm putting this down to a bug in the library. 

Assuming it is a bug with the library, it needs to be fixed as soon as possible because otherwise verified bots with the guild members intent but without the presence intent aren't able to fill their user cache.

**Edit:** I have since discovered that DownloadUsersAsync() doesn't work in the ready or guild available handlers, but using it in the connected / shardconnected handlers works great! I hope this helps.

**Comment by DaNeubi** [comment]
> 
> 
> Just in case anybody hasn't sussed this out, the GetUser(id) method only interacts with the client's cache. If you're having issues with the cache and need to get someone by ID, use GetUserAsync(id) which directly queries Discord's REST API.
> 
> I found that on the nightly builds, neither `AlwaysDownloadUsers = true` nor `SocketGuild.DownloadUsersAsync()` work, despite having the GuildMembers and Guild intents enabled. They don't throw an error, they just get stuck.
> 
> If I enable the presence intents, AlwaysDownloadUsers works again. I don't see why presence data should be required to get the members of the server, so I'm putting this down to a bug in the library.
> 
> Assuming it is a bug with the library, it needs to be fixed as soon as possible because otherwise verified bots with the guild members intent but without the presence intent aren't able to fill their user cache.
> 
> **Edit:** I have since discovered that DownloadUsersAsync() doesn't work in the ready or guild available handlers, but using it in the connected / shardconnected handlers works great! I hope this helps.

Indeed I can confirm, that you need both Intents. Only Server Member Intent does not work.
This fixed it for me.

**Comment by ARRAMAGA** [comment]
> If I enable the presence intents

Can you write in more detail what exactly needs to be done to fix the problem?

**Comment by RheaAyase** [comment]
I'd like to point out that this ticket is NOT about the presence intent and its effect on user cache.
It is a known fact that presence intent is required to download users.

![2020-11-14_23-23-08](https://user-images.githubusercontent.com/13802951/99158173-5ff6e080-26d0-11eb-9d3a-8d58f42f534e.png)

---

This ticket is about a rare issue where the user is in fact missing, and a functioning DownloadUsers method does not populate the cache correctly - neither does the user activity and received messages. The user is still missing.

**Comment by DaNeubi** [comment]
@ARRAMAGA
> 
> 
> > If I enable the presence intents
> 
> Can you write in more detail what exactly needs to be done to fix the problem?

You need to go to the Discord Developer Website, select your Bot(s), go to the Menu called Bot and check both Intent options.

**Comment by ARRAMAGA** [comment]
> You need to go to the Discord Developer Website, select your Bot(s), go to the Menu called Bot and check both Intent options.

I suffered for 3 days, and the decision was so... unexpected. Thanks for the help

**Comment by xilence222** [comment]
I currently have a bot with Member and Presence intent set on the developer portal, but DownloadUsersAsync().Wait() never returns and the DownloadedUsers event never fires.

I'm using the latest dev snapshot.

**Comment by TheKingEagle** [comment]
I have the Members intent enabled, but not the presence intent.  After some looking around, someone suggested calling DownloadUsersAsync() from the ShardConnected event. This half worked, though some guilds were still not returning any users. I was able to fix that by going through each guild individually,  and downloading users that way. So far, it seems to be working for me. It's likely not ideal, but it *does* work.

**Comment by RheaAyase** [comment]
Please do __**not**__ carry this discussion in this ticket, it's not about anything related to intents!
Please continue in https://github.com/discord-net/Discord.Net/issues/1679

**Comment by TheKingEagle** [comment]
Oh, sorry. I didn't realize I was not permitted to contribute a comment into an open issue regarding the same problem many other people were having, with a proposed workaround that solved said issue.

**Comment by Pdzly** [comment]
I have still this issue is there anything other than the intentions in DC to active? Because if i search someone it gets null
