### ISSUE TITLE
ModifyAsync resets allowed mentions property

### ISSUE THREAD

**Issue by xXBuilderBXx** [RogueException/Discord.Net#1610]
Not sure if this is an issue with Discord or the lib but the allowed mentions property gets reset whenever you edit a message.
ModifyAsync only allows you to edit the message content and embeds with no other way to set allowed mentions.
![Image](https://i.imgur.com/MCUWIVd.png)

**Comment by SubZero0** [comment]
We don't send anything related to allowed mentions in the request, so it's an issue with Discord.
Probably related: https://github.com/discord/discord-api-docs/issues/1864

**Comment by xXBuilderBXx** [comment]
The commit you linked has a comment saying "The issue seems to be that if you patch a message without the allowed_mentions property"
Does that mean it's possible discord.net could add this to modifyasync that might fix this.

**Comment by SubZero0** [comment]
I don't think we should try to fix what is probably a Discord oversight, they will probably do it sooner or later. It shouldn't affect the clients too since edited mentions don't actually ping.

Besides that, the property isn't mentioned in the current discord docs or any open PR for it and we can't know the current state of the allowed_mentions (not sure if the current mention properties are directly related to it since they were there before it existed iirc), so we would need to either build it with what we have and send something not explicitly asked or make the property required and not optional, that also doesn't look like a good way to solve it.
