### ISSUE TITLE
@everyone isn't considered a mention

### ISSUE THREAD

**Issue by Azthenix** [RogueException/Discord.Net#1617]
I'm trying to run some code when someone uses @everyone, but when I tried to use @everyone MentionedRoles and MentionedUsers were empty.

**Comment by MarkusG** [comment]
`MentionedRoles` is likely populated by parsing the message for literal mentions (e.g. `<@72080813948153856>`, which `@everyone` is not. The solution is to check the message content for `@everyone` verbatim rather than checking the `MentionedRoles` property.

EDIT: Nevermind. It looks like [it should](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Rest/Entities/Messages/MessageHelper.cs#L227) parse `@everyone` as a role.

**Comment by Azthenix** [comment]
I should also mention that in the message.Content the @everyone isn't turned into something like <@!> and so is @here apparently

below is from a messagelog from my bot
```
9/5/2020 2:07:51 AM:: general:: general:: Azthenix#4909:: Azthenix:: @everyone:: 3713990
9/5/2020 2:07:59 AM:: general:: general:: Azthenix#4909:: Azthenix:: @here:: 3713990
9/5/2020 2:08:11 AM:: general:: general:: Azthenix#4909:: Azthenix:: <@&751501316253155329>:: 3713990
9/5/2020 2:08:17 AM:: general:: general:: Azthenix#4909:: Azthenix:: <@!415742845228417034>:: 3713990
```

**Comment by MarkusG** [comment]
Like I said, `@everyone` and `@here` don't follow the same format as mentioning a user/channel/role. There are special cases that should parse them into the `MentionedRoles` property. But under the hood it just matches against `@everyone` and `@here`, so if you match it yourself it'll work just as well.

**Comment by Azthenix** [comment]
but what if someone write @everyone but doesn't mention everyone

like putting it between 2 ```s where it is read as code snippet

**Comment by Azthenix** [comment]
I can probably write something to parse check if it was inside a code snippet or not but just checking in case there's an easier way to handle it
