### ISSUE TITLE
GetUsers with out Presence Intent

### ISSUE THREAD

**Issue by TheAscorbic** [RogueException/Discord.Net#1689]
Hello,

Having an issue where the full user list is not being provided without the Presence Intent enabled.  I was informed by Discord support that I do not need the Presence Intent to get the full user list.  Here is their response to my request.  I have updated to the most recent version and I am still having this issue.

Waterloo (Discord)Nov 20, 2020, 9:23 PST
Hey there,
I appreciate your patience with my reply here. Currently, GetUsers doesn't require access to the Presence Intent in any way. My best recommendation here is to review your library's documentation or ask in their support server for advise on implementing this without needing the Presence Intent. Please let me know if you have any other questions in the meantime though.

**Comment by SubZero0** [comment]
The discord employee is specifically talking about the REST endpoint that has nothing to do with gateway intents. The `GetUser` method in this lib is a cache lookup, so if you don't have that intent, you won't receive any (and won't be able to get them with it, only via rest).

You can enable it in the dev portal if needed and add the intent in your config if on nightly and specifying them.

Edit: I'm talking about the Guild Members privileged intent, the Presence one has nothing to do with it.

**Comment by TheAscorbic** [comment]
I am able to get it when the Presence Intent is enabled.  Specifically Guild.Users, when Presence is enabled I have a full user list, when it is turned off, I only have the owner and the bot.  What I am seeing in debugging does not reflect what you are saying.

**Comment by SubZero0** [comment]
That's because you are talking about [Guild Create](https://discord.com/developers/docs/topics/gateway#guild-create) that is received when connecting that has a list of users (partial for large servers) and it's only sent if you have both intents enabled (I don't know why Discord chose to limit it there only when you had both).

But you can achieve the same by requesting the users via gateway ([Request Guild Members](https://discord.com/developers/docs/topics/gateway#request-guild-members)) that is called downloading users in this library and it's done by methods called `DownloadUsersAsync` present in the client and guild object.

With the Guild Members Intent alone, you can get the full user list by enabling `AlwaysDownloadUsers` in the client configuration (`DiscordSocketConfig`). It might take a bit more depending on the size of the shard (there's a ratelimit of 120 requests per minute, so you can request up to 177 guilds per minute) but it will get you the full user list. I would **highly recommend using the nightly version** since it has some bugfixes related to the changes.

**Comment by TheAscorbic** [comment]
AlwaysDownloadUsers works, thanks so much for pointing me to that.

**Comment by SubZero0** [comment]
Glad to help, if you have any other issues, feel free to open another issue or ask them in our channel (#dotnet_discord-net) in the Discord API guild (there's an invite in the readme).
