### ISSUE TITLE
Rate limit: GET users/@me

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1837]
This doesn't seem healthy, and given the places where it's used, it doesn't seem to be achievable from user code, is it? I mean, I hope that spamming login would trigger some other issues first lol...

![image](https://user-images.githubusercontent.com/13802951/117927870-18f24c80-b2fb-11eb-80b9-bd2267adbafa.png)

**Comment by RheaAyase** [comment]
As a side note, it does happen from login but the ratelimit is initially triggered elsewhere and this is just a sideeffect, however a silly one that probably shouldn't happen, or should just throw an exception.. or something? Sounds like particularly nasty one to be ignored with but a debug message (not even warning/error level.)

**Comment by RheaAyase** [comment]
I'm just gonna close this so it doesn't hang here for years. It's not like anyone will do anything about login ratelimit severity.

**Comment by SubZero0** [comment]
I see it from time to time but I never found the main issue that triggers it so there's no way to fix it.

I don't know what version you are using, but an issue that made d.net do unwarranted rest requests was fixed in 2.4.0 with #1835 and the person that found it was also experiencing the same rate limits so I believe it's that.

**Comment by RheaAyase** [comment]
Good info thank you
