### ISSUE TITLE
I can't to get list of users from my server 

### ISSUE THREAD

**Issue by basi1ik** [RogueException/Discord.Net#1891]

**Comment by zbroderson** [comment]
intents are here, please do some light reading. to specify intents, please update to 2.4.1+. https://discordapp.com/channels/81384788765712384/381871767846780928/770678489404932146 and also join https://discord.gg/discord-developers for lots of info straight from the horses mouth (100% match)

**Comment by Draco18s** [comment]
> intents are here, please do some light reading. to specify intents, please update to 2.4.1+. https://discordapp.com/channels/81384788765712384/381871767846780928/770678489404932146 and also join https://discord.gg/discord-developers for lots of info straight from the horses mouth (100% match)

That channel link no longer works. Even after accepting that server invite, I cannot view that message.
If that message was posted to some other server, I can't view it without being a member of *that* server. It would be far better to *post the relevant context* here.

Edit: It was *this* server: discord.gg/discord-api

**Comment by LionAG** [comment]
Your problem might be not specifying necessary gateway intents. 

You need to specify it as:

`GatewayIntents = GatewayIntents.GuildMembers | GatewayIntents.Guilds `

Otherwise you'll get error 50001 "Missing access".
Keep in mind that GatewayIntents.GuildMembers is a privileged intent and must be enabled in the developer portal.

**Comment by Draco18s** [comment]
Yeah I figured it out.
