### ISSUE TITLE
Thread Support

### ISSUE THREAD

**Issue by Cisien** [RogueException/Discord.Net#1899]
I understand it's still very early in the rollout of thread support to discord communities, but large public communities are starting have the option of enabling this feature in their servers. Unfortunately, bots written in discord.net cannot see the messages sent in threads, and therefore cannot moderate threads.

Is thread support on the roadmap for discord.net? Or should we seek out alternatives?

**Comment by xXBuilderBXx** [comment]
Gateway events for threads are on version 9 of the Discord API atm which would probably need some major changes to the code also it dosen't even support buttons and slash commands yet either so threads are gonna take a while.

**Comment by JimboJacksonBroDudeMan** [comment]
IMO this one should be waaaaaaay higher priority than slash commands or buttons.   a lot of us use discord.net for moderation functions so having our bots not being able to see threads complicates everything.

**Comment by Cisien** [comment]
It means that discord.net isn't suitable for purpose on servers that wish to use this feature.

**Comment by JimboJacksonBroDudeMan** [comment]
So your solution here is to completely rewrite our bots using something else.  Got it.  Very helpful.

**Comment by Cisien** [comment]
I'm not affiliated with this project. For what it's worth; we are re-writing our bots to use other libraries that have support for threads.

**Comment by AntiTcb** [comment]
You don't *have* to complete re-write your bots; you can have multiple applications running simultaneously. Keep your existing bot in D.NET, and you're free to also have an application running using a separate API library with the support for the newer Discord features that this library doesn't support yet.

**Comment by Cisien** [comment]
Yeah, sure. That's AN option, but a terrible one.

**Comment by SubZero0** [comment]
I understand how critical threads can be for some, I'll try to get some time to add support to them in the latest version.
So applications can, at least, receive and process messages sent in those.

For now, my plan is doing it in a similar way as private channels, as not keeping them in cache (unlike text channels), and I'll probably need to request the ability to use threads in a private server to Discord so I can test it.

**Comment by JimboJacksonBroDudeMan** [comment]
> I understand how critical threads can be for some, I'll try to get some time to add support to them in the latest version.
> So applications can, at least, receive and process messages sent in those.
> 
> For now, my plan is doing it in a similar way as private channels, as not keeping them in cache (unlike text channels), and I'll probably need to request the ability to use threads in a private server to Discord so I can test it.

Check your servers.  My partnered server didnt have it enabled till after the partnered happy hour today but a server of mine with 7 members had it enabled before that and another with a few hundred had it before as well.

I checked two of my friend's private servers and both have threads enabled already.

**Comment by SubZero0** [comment]
To start, I wrote two possible solutions:

#1901 - Change the IMessage.Channel property from `IMessageChannel` to `Cacheable<IMessageChannel, ulong>`
**Pro**: this would make pretty easy to know if the channel is present or not, while making people adjust their code (won't get surprised by the change since they will need to redo the logic as it'll break)
**Con**: sending messages isn't as trivial as before as Channel could not be there, would require adding SendMessage and SendFile to the client and changing from `context.Channel.SendMessageAsync(...` to `context.Client.SendMessageAsync(channelId, ...` if they don't want to possibly download the channel

#1902 - Create a new channel type: `UnknownChannel`
**Pro**: won't require any changes as Channel will still exist as an IMessageChannel, no weirdness to send messages/files
**Con**: logic from before might not work well, since this new channel type wasnt considered when they built their applications (Name would be null and different logic as this channel *at the moment* could only be a thread channel but not classified as one since the id is the only thing present), would require to get the actual channel ("download" by REST) to do more than send messages/files

At this moment, I'm leaning towards the second because one of the two:
- If I decide to cache thread channels, the lib consumer will barely notice the existance of `SocketUnknownChannel` when a proper `SocketThreadChannel` is added by a following PR.
- If I don't, it's still "plug'n'play" and trivial to send messages, except that when using the lib, it might be needed to be careful with `SocketUnknownChannel`s and deal with it differently since it would be needed to get the channel by REST (for now, the only case for an unknown channel is a thread).

**Comment by quinchs** [comment]
I mean... labs has threads, i can open a PR and we can work from there to implement them here @SubZero0

**Comment by IS4Code** [comment]
> Gateway events for threads are on version 9 of the Discord API atm which would probably need some major changes to the code also it dosen't even support buttons and slash commands yet either so threads are gonna take a while.

Well the version in Discord.Net was bumped to 9 two months ago and seems to work so...

**Comment by Sasino97** [comment]
This is a major feature lacking, it should be priority number 1 for Discord.NET
Meanwhile, I think I'm gonna write a second bot in JS to moderate threads

**Comment by MathieuDR** [comment]
> r feature lacking, it should be priority number 1 for Discord.NET
> Meanwhile, I think I'm gonna write a second bot in JS to moderate threads

You could always check Discord.Net Labs, it has some more new experimental features

**Comment by IS4Code** [comment]
> You could always check Discord.Net Labs, it has some more new experimental features

Doesn't seem like the support for creating threads is there either, but hopefully it will come sooner.

**Comment by mcmonkey4eva** [comment]
It's in a branch @ https://github.com/Discord-Net-Labs/Discord.Net-Labs/tree/feature/threads

**Comment by alikindsys** [comment]
> It's in a branch @ https://github.com/Discord-Net-Labs/Discord.Net-Labs/tree/feature/threads

its actually already merged into labs, and is [released on v3.0](https://github.com/Discord-Net-Labs/Discord.Net-Labs/releases/tag/3.0).

**Comment by MrCakeSlayer** [comment]
This has now been implemented via the merged labs PR (#1923)
