### ISSUE TITLE
Message received handler blocking gateway task

### ISSUE THREAD

**Issue by ghost** [RogueException/Discord.Net#1907]
Upon implementing my database I am getting a warning upon using a command 
`Message received handler is blocking the gateway task`
This leads to my bot being frozen for a few seconds and by frozen I mean it stops responding to any commands 
Below is the link to GitHub repository incase you will like to see the code 
https://GitHub.com/Not-Storm/Evelin.NET

**Comment by MichailiK** [comment]
When you receive an event (in your case, the message receive event), you will be preventing Discord.Net from processing any data Discord sends, until your event handler finishes. This is because your event handler gets run in the "Gateway Task", which receives & processes data from Discord.

For more details & solutions, check out the docs: https://docs.stillu.cc/faq/commands/general.html#discordnet-keeps-saying-that-a-messagereceived-handler-is-blocking-the-gateway-what-should-i-do

**Comment by ghost** [comment]
@MichailiK Hello and thank you for your response,
So upon going through the docs I came to know that I should change my RunMode to "Async", so is there a way I change the run mode to Async just for the command handler or event ? I don't want to make it default for the whole project itself

**Comment by MichailiK** [comment]
Use an async RunMode for any commands that might take a long time to complete (i.e. commands that access the database) as a CommandAttribute, just like in the example shown in the FAQ.

**Comment by ghost** [comment]
@MichailiK Hello and thanks,
Just realized it was my database taking its sweet time to get the prefix
