### ISSUE TITLE
Sharding over multiple hosts

### ISSUE THREAD

**Issue by pollux** [RogueException/Discord.Net#1919]
Hello,

I'm fairly new to Discord.NET and currently working on a sharded discord bot. The DiscordShardedClient class works perfectly fine so far.

Even if it's not a necessity right now since my bot is in closed alpha and doesn't come anywhere near the limitations from discord (servers per shard) I would like to know how to be able to split the bots shards over multiple hosts instead of different shards on one single host.

I looked through the documentation and also opened and closed GitHub issues of this repository but couldn't find any hint so far on how to achieve this.

**Comment by Joe4evr** [comment]
For splitting across multiple processes/hosts, you need to use just the `DiscordSocketClient` and provide it with [a respective `ShardId` (0-based) and the `TotalShards`](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/DiscordSocketConfig.cs#L44-L52). Everything else is handled for you.

**Comment by pollux** [comment]
So.. I could build a small console app that gets the recommended shard count from discord and then spawns the shards in a kubernetes cluster across multiple hosts.

Does Discord or Discord.NET handle which server is on which shard automatically? Like.. will this be random every time a shard is created or destroyed? Or will it be a fixed shard number for each server?

**Comment by Joe4evr** [comment]
[`shard_id = (guild_id >> 22) % num_shards`](https://discord.com/developers/docs/topics/gateway#sharding) (DMs are always sent to shard 0)
Discord itself handles which shard will receive the relevant information/events by the above formula, which isn't *random* but it's also not at all guaranteed to be equally distributed. Plus, if you're going to add/remove shards, you need to restart all other shards to synchronize because that information is only sent as part of IDENTIFY.

This is mainly why the common advice is *do not even bother thinking about sharding* if your bot is not close to 2000 guilds in the first place. You're much better off using only a single instance and not worry about sharding if you don't even know that your bot will be popular enough to warrant the effort.
