### ISSUE TITLE
Update causes _client.CurrentUser to be null (when restarting the _client)

### ISSUE THREAD

**Issue by dimitryraymond** [RogueException/Discord.Net#1979]
Issue was introduced when I updated from 2.4 to 3.0

To reproduce I have a /reload command that does this

``` c#
_client.LogoutAsync();
_client.StopAsync();
//wait 2 seconds
_client.LoginAsync(TokenType.Bot, BotToken);
_client.StartAsync();
```
In logs, I get that the Gateway `Resumed previous session`

Upon next `_client.MessageReceived` event, `_client.CurrentUser => NULL`

Here are some of the other values in debug
`_client.ConnectionState => Connected`
`_client.LoginState => LoggedIn`
`_client.Rest.CurrentUser => Has Value`
`_client.Rest.LoginState => LoggedOut`

**Comment by quinchs** [comment]
This is quite the issue

It seems like `_client.Rest.LoginState => LoggedOut` is maintained throughout the client lifecycle due to the nature of the `DiscordSocketRestClient`.

`_client.CurrentUser` is set to null apon calling `LogoutAsync`, it doesn't seem to clear `_client.Rest.CurrentUser` tho.

The main issue with our current approach is that we rely on the [ready](https://discord.com/developers/docs/topics/gateway#ready-ready-event-fields) event to get our current user. When resuming a session we don't get the ready event, instead we receive a [resumed](https://discord.com/developers/docs/topics/gateway#resumed) event which doesn't contain information about the current user. We can interoperate that if we're resuming we can restore the current user from the previous session.
