### ISSUE TITLE
Suppress Embeds

### ISSUE THREAD

**Issue by bman46** [RogueException/Discord.Net#2020]
Before 3.0.0 there used to be a method similar to `context.message.suppressEmbeds()` that would remove embeds on messages from other users; However, it appears that it has been removed. I have also tried to do `await context.Message.ModifyAsync(item => { item.Flags = MessageFlags.SuppressEmbeds; });` but that results in the error `System.ArgumentException: Argument cannot be blank. (Parameter 'Content')`. 

According to the [Discord API docs](https://discord.com/developers/docs/resources/channel#edit-message), other users are allowed to edit flags as long as they have the Manage messages permission and the SuppressEmbeds flag can be set/unset after sending the message.

**Comment by Dulatr** [comment]
I know this might be an old issue, but it's exactly what I'm experiencing now in version `3.15.0`. Is this just not possible anymore from Discord's end?

Since I didn't see any suppress method exposed, I'm calling it similarly:

```cs
await message.ModifyAsync(p =>
{
  if (p.Flags is { IsSpecified: true, Value: not null })
	  p.Flags = MessageFlags.SuppressEmbeds;
});
```

The optional content property on the `MessageProperties` class is also not specified at that point, I'm pretty sure I've added all the permissions needed such as `Manage Messages`
