### ISSUE TITLE
Diagnosing Reconnects

### ISSUE THREAD

**Issue by dimitryraymond** [RogueException/Discord.Net#2101]
This is in 3.1.0 (just upgraded to 3.3.0)

Help me help you diagnose the reconnect issues I sometimes have.
In my environment, I'm running 2 instances of my discord bot, each managing their own DiscordSocketClient.
I have a Hangfire background job that runs this logic every minute:

``` c#
public async Task ReconnectIfExpectedOnlineAsync()
{
    if(ConnectionStateGoal == ConnectionState.Connected && ConnectionState == ConnectionState.Disconnected)
    {
        await LoginAsync(); // basically await _client.LoginAsync, await _client.SetStatusAsync, await _client.StartAsync
        //logs and sms notification
    }
}
```

The reconnect works, but most of the time this causes that instance to stop hitting the MessageReceived handler.

I eventually fixed the long running task / gateway blocking issues, which reduced the # of times the reconnect happens significantly.
But the bot still reconnects on average once every 2 days. 
And the MessageReceived issue is still happening most of the time.

According to docs, once you fix the gateway blocking issues, the bot should always stay up. So today, I changed the background job to run every 3 minutes, in case you already handle that.

So my questions are:
* Am I reconnecting correctly in the first place?
* If you want to debug the reconnection issue, what variables should I monitor?
* What to do about the MessageReceived handler not hitting?

**Comment by csmir** [comment]
Reconnection is not an event controlled by the library, and is often caused by [this](https://discord.com/developers/docs/topics/gateway#reconnect). Reconnections are by default a lot more frequent than once every 2 days. There is no way to *get rid* of them. Discord.Net embraces this behavior and makes sure that all current behavior going over the gateway is not missed, and properly handled after the reconnect.

Gateway blocking has nothing to do with reconnection, and more so about how you handle tasks inside the gateway thread. The best way to resolve such behavior is by moving non-direct gateway communication up into tasks, to resolve blocks and not have the bot flood under a bucket of unhandled dispatches.

I also can confirm that a hangfire job handling this is unnecessary, as the library already does reconnection on its own. As I said previously, Discord.Net embraces reconnection and handles it accordingly inside the connection manager. The developer docs imply that reconnection resumes the previous session naturally, so logging in again *may* actually be the issue as to why your handlers are not hitting. You are not continuing your previous session like this, you are moving to a new one.

Debugging the reconnection issue is not possible, as this dispatch is sent out by Discord. Their hosting is something we cannot monitor, and so the moments when reconnects happen are often completely random.

**Comment by dimitryraymond** [comment]
Thanks!

I haven't had any connection issues since a week ago.
