### ISSUE TITLE
[Bug]: Voice channel messages result in Unknown Channel

### ISSUE THREAD

**Issue by LazyBoot** [RogueException/Discord.Net#2255]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I get an "Unknown Channel" error whenever someone sends a message in a voice channel.

### Version

3.5.0

### Logs

[2022-04-20 22:24:37 +00:00] WRN <Gateway>      Unknown Channel (MESSAGE_CREATE Channel=724752911137243196).

### Packages

Fergun.Interactive - 1.5.0

**Comment by MrCakeSlayer** [comment]
Discord hasn't fully released text messages/channels on voice channels yet. Discord.Net will support it once it's been released.

**Comment by LazyBoot** [comment]
That's disappointing to hear... One of the main server me and my bot is in has had that enabled for a couple of weeks now already, but obviously the bot doesn't know what to do with those yet.

**Comment by MrCakeSlayer** [comment]
@LazyBoot Labs had a PR ready for this, if you urgently need this feature you could clone DNet and implement the PR manually on your local copy for use. It likely won't be added to the main repo until the feature launches.

PR: https://github.com/Discord-Net-Labs/Discord.Net-Labs/pull/280

Also note, this PR is slightly outdated, it may work, it may not. Since Discord constantly changes things, so you may need to make modifications yourself to keep it working until it's officially supported.

**Comment by MrCakeSlayer** [comment]
Update: quin migrated the PR to the main repo: https://github.com/discord-net/Discord.Net/pull/2269

**Comment by MrCakeSlayer** [comment]
PR was merged, closing issue.
