### ISSUE TITLE
[Bug]: Value of IsPinned is not updated after PinAsync is called

### ISSUE THREAD

**Issue by bub-bl** [RogueException/Discord.Net#2309]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When i call PinAsync from MessageReceived event, the value of IsPinned property is not updated, the same thing appear for other property like IsSuppressed etc. But when is call PinAsync, the MessageUpdated event is called and the value of IsPinned is updated but non updated in MessageReceived event

### Version

3.6.1

### Logs

No logs or stack trace

### Sample

```cs
 private async Task OnMessageReceived(SocketMessage message)
        {
            var m = (message as SocketUserMessage);
            
            _logger.LogDebug("Before: " + m.IsPinned);
            await m.PinAsync();
            _logger.LogDebug("After: " + m.IsPinned);
        }
```

### Packages

Discord.Net.Commands V3.6.1, 
Discord.Net.Core V3.6.1, 
Discord.Net.Interactions V3.6.1, 
Discord.Net.Rest V3.6.1, 
Discord.Net.Webhook V3.6.1, 
Discord.Net.WebSocket V3.6.1

**Comment by Tripletri** [comment]
Message, that you receive from event it is a snapshot of what was sent. When you calling `PinAsync()` you making request to DiscordApi to pin it. [Discord.Net](https://github.com/discord-net/Discord.Net) doesn’t provide a message state update. It made probably due to _single source of truth_. So, if you want to track state change of message, you should implement it be yourself. Worth mention, that [DiscordAPI](https://discord.com/developers/docs/resources/channel#pin-message) returns a 204 empty response on success, that makes pessimistic update impossible.
