### ISSUE TITLE
Suspicious fragments found by PVS-Studio Static Analyzer

### ISSUE THREAD

**Issue by NikiPn** [RogueException/Discord.Net#2403]
Hello!

I checked your project with the PVS-Studio analyzer. I found a number of suspicious code fragments. Would you like to take a look at them? I wrote an [article](https://pvs-studio.com/en/blog/posts/csharp/0974/) where I described the found issues. The article contains the most interesting analyzer's warnings. Using [the free PVS-Studio license for open-source projects](https://pvs-studio.com/en/order/open-source-license/), you can get the full analysis result.

**Comment by csmir** [comment]
With all due respect, you mention in your article: 'Maybe PVS-Studio can fix some hidden issues' but you have made no effort to fixing them? While this article is helpful and I would like to thank you for your effort, you are implying that fixes would be made from the studio (with you in lead) itself, yet no such PR has appeared.

**Comment by Quahu** [comment]
> With all due respect, you mention in your article: 'Maybe PVS-Studio can fix some hidden issues' but you have made no effort to fixing them? While this article is helpful and I would like to thank you for your effort, you are implying that fixes would be made from the studio (with you in lead) itself, yet no such PR has appeared.

I believe they were just referring to their product, PVS-Studio.

That said, this seems to just be a low-effort way of advertising it. Instead of writing an article that just lists these inspections, you could've instead fixed the problems? With a PR like that, you could then explain how you found out about these issues, i.e. how your product came in handy.

You've also only listed "the most interesting" warnings as essentially a demo (again, advertisement) of it, despite, for example, `Issue 12` being something as basic as a redundant ternary statement.
From experience, VS/Roslyn analyzers or ReSharper would've picked up on most if not all of the things you've listed, so I don't think it's anything worthwhile.

**Comment by csmir** [comment]
I've gone ahead and decided to push the suggested changes that seem reasonable to do, in order to close this issue.
