### ISSUE TITLE
[Feature Request] Support interacting with original interaction response via interaction token

### ISSUE THREAD

**Issue by GNUGradyn** [RogueException/Discord.Net#2412]
Discords REST API supports retrieving/modifying/deleting the original response to an interaction using only the interaction token (and the app ID/authentication, of course). This endpoint is documented here https://discord.com/developers/docs/interactions/receiving-and-responding#get-original-interaction-response

From talking to people on the Discord it sounds like the only currently supported solution is retrieving the message ID of the response *after* sending it

**Comment by csmir** [comment]
This makes no sense to me. `GetOriginalResponseAsync` is documented in the interaction object. What exactly are you trying to achieve?

**Comment by GNUGradyn** [comment]
Because there is no way to retrieve the interaction object at a later time. I need to edit a response (perhaps days/weeks later) even if the bot has been rebooted or from another pod. 

Therefore, some sort of identifier I can store in my database and use later to reference the interaction is needed. 

It is preferable to do it this way then to send the response and store the message id in the database because if the message is sent and the database operation fails an error would have to be displayed to the user after the interaction already appears to succeed. I'm sure there are plenty of other use cases where the database operation must come first

**Comment by csmir** [comment]
You only get 15 minutes to work with the token. After that, you will need to use the message ID like normal.

**Comment by GNUGradyn** [comment]
Oh dang. I was not aware of this limitation. I suppose this wouldn't be that useful then

**Comment by emorell96** [comment]
Is there a way to get the original interaction from the socket client? (using only ids/tokens) I am asking because sometimes our bot uses MassTransit to log or do something in the background but the interaction or modal for that matter usually cannot be serialized. So I cannot send those over RabbitMQ or whatever other transport I use with MassTransit. I usually overcome this with passing the ids and getting the objects in the consumers, but I haven't found a way to do this with interactions or modals.

Thanks!

**Comment by GNUGradyn** [comment]
@emorell96 you'll have to respond first and store the ID of the response, which you can then use like any other message
