### ISSUE TITLE
Update from 2.3.1 to 3.8.1 broken my bot.

### ISSUE THREAD

**Issue by TheToi** [RogueException/Discord.Net#2482]
[https://i.imgur.com/tLrhO17.png](url)

When a client type a command like  "$help", my bot receive always it, but the SocketMessage Content is empty since i migrated to discord.net 3.8.1!
As you can see on the screenshot above, the SocketMessage is not void, it contains correct Author and Guild, but now the message is empty.
What can i do ? I wanted to go back in 2.3.1 but i can't anymore.

**Comment by Misha-133** [comment]
You need to add `GatewayIntents.MessageContent` intent to your `DiscordSocketConfig` and enable it on dev portal

**Comment by TheToi** [comment]
I just did it, now the MessageReceived event is no more triggered so it's even worse.
I managed to make it works by setting `GatewayIntents.All`
Thx for the help anyway, without that i would not find it.

**Comment by yutamago** [comment]
This issue is not related to 3.8.1.

My bot started having the exact same issue just yesterday and I never updated it past 2.4.0.
The Discord API now **requires** you to state the GatewayIntent in the `DiscordSocketConfig` and enable it in the dev portal.

It says in the documentation that `GatewayIntents.All` is not recommended, because it can produce memory leaks.
Instead you should use `GatewayIntents.AllUnprivileged | GatewayIntents.MessageContent`

**Comment by TheToi** [comment]
Thank a lot !
