### ISSUE TITLE
[Bug]: Unicode character `↔` and emoji `:left_right_arrow:` fail Emoji.TryParse

### ISSUE THREAD

**Issue by Panthr75** [RogueException/Discord.Net#2779]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When using `Emoji.TryParse` with the unicode character `↔`, it fails.

### Version

3.12.0

### Logs

```shell
N/A
```

### Sample

```cs
System.DiagnosticsDebug.Assert(Emoji.TryParse("↔", out Emoji _)); // Error: Assertion failed
System.DiagnosticsDebug.Assert(Emoji.TryParse(":left_right_arrow:", out Emoji _)); // Error: Assertion failed
```

### Packages

- [Forked Discord.NET v4.1.0/Bonnel Lib](https://github.com/Panthr75/Based-Discord.Net/tree/bonnel-lib) (Emoji.TryParse has not been altered)
- Bonnel

### Environment

- **OS**: Windows 10
- **Arch**: x64
- **SDK**: .NET 7.0

**Comment by DeclanFrampton** [comment]
You are not using Assert accordingly, check documentation here [Microsoft Assert]( https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert?view=net-7.0#system-diagnostics-debug-assert(system-boolean-system-string))

As for parsing both "↔" and "`:left_right_arrow:`", both are successful since the NamesAndUnicodes KPV contain the key and value. In both your fork and master

![image](https://github.com/discord-net/Discord.Net/assets/26311803/0f8a7a09-1da7-4185-b8ef-49c644565a37)


Fork: 
https://github.com/Panthr75/Based-Discord.Net/blob/7292ea3f7f69e7f610470890058c17f93cc07ede/src/Discord.Net.Core/Entities/Emotes/Emoji.cs#L2541

Original Master: 
https://github.com/discord-net/Discord.Net/blob/8baf913c9d4e5504384062c8d74fe8f3f70efcd0/src/Discord.Net.Core/Entities/Emotes/Emoji.cs#L2496

**Comment by Panthr75** [comment]
Weird. I guess I'll have to take a deeper look into the code that's uses Emoji.TryParse
