### ISSUE TITLE
Possible to stream audio directly for opus-encoded audio source?

### ISSUE THREAD

**Issue by Inirit** [RogueException/Discord.Net#691]
This is more of a question than an issue, but I was having trouble with this on my own so I wanted to ask here.

Is there a supported flow for streaming an audio source that's already opus-encoded (as opposed to a PCM source that gets encoded at run time)?

I see the method for creating an opus stream [here](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Audio/AudioClient.cs#L143), but directly copying a stream with a buffer of an opus-encoded file into a BufferedWriteStream (the returned stream type for CreateOpusStream) doesn't work. I don't have the exception or stack trace on hand at the moment, but it was about an index being out of bounds on [this line](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Audio/Streams/BufferedWriteStream.cs#L147).

Looking at the method CreatePCMStream, a BufferedWriteStream gets wrapped in an OpusEncodeStream and the OpusEncodeStream chunks the data to be passed to the BufferedWriteStream under the hood. It seems BufferedWriteStream expects its input data to be chunked up to a maximum size (the buffer arrays being defined [here](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Audio/Streams/BufferedWriteStream.cs#L57)), so I suspect that's why directly writing to a BufferedWriteStream with an arbitrary length of data doesn't work.

For some additional context, I have two reasons why I'd like to do this. The first is to eliminate the dependency on a native dll (opus.dll), I've been able to run my code on Windows and Linux with a separate dll compiled for each platform, but it would easier/cleaner if I could assume the audio sources had an expected encoding and the bytes could be streamed as-is. The second is for what I suspect could be performance reasons, I have a Raspberry Pi that I'm running my code on and while audio streaming works I'd prefer it keep it as lightweight as I can due to its limited resources. I suspect eliminating the run time encoding could aid that quite a bit (though I don't have numbers to back up that suspicion).

**Comment by FiniteReality** [comment]
You can create direct opus streams (CreateOpusStream and CreateDirectOpusStream) if you need to pass raw Opus, but it is discouraged because it means that you cannot encode taking into account packet loss and error correction.

Additionally, as long as you install libopus/libsodium on the platforms you wish to use it on, .NET will automatically detect which binary to use automatically. You should also not worry that much about encoding performance, as Opus is designed to be an efficient encoding and you can easily tweak the numbers (Opus has a *lot* of options) so that you can get a high-quality, fast encode.
