### ISSUE TITLE
Permission: External Emotes always false

### ISSUE THREAD

**Issue by xXBuilderBXx** [RogueException/Discord.Net#869]
When running this code it always returns false even if the bot has the permission i have tested this in 2 guilds with full perms and must be a bug with the new permission change here https://github.com/RogueException/Discord.Net/commit/f9963380a7a33c826507bebf555294b72bace633
https://weeb.hacked-your.webcam/ccaf23b.png

**Comment by Chris-Johnston** [comment]
~~Unsure if issue is fixed by #866 , unable to test that currently.~~ Added commit to address this issue.

Can confirm issue is happening. Only appears to affect `GuildPermissions`. Calculation of flags appears to be correct, as the `RawValue` from a guild with all permissions enabled gives `2146696447`. When calculating the flag for `UseExternalEmojis`, `2146696447 & 0x00040000 = 0`. The incorrect `RawValue` could be a result of the out of order parameter in `GuildPermissions` constructor.

**Comment by Chris-Johnston** [comment]
The `All` constant for GuildPermissions is missing the flag for `UseExternalEmojis`. When `Permissions.ResolveGuild` encounters the Administrator permission, it returns `All` which results in the error.

https://github.com/RogueException/Discord.Net/blob/f9963380a7a33c826507bebf555294b72bace633/src/Discord.Net.Core/Entities/Permissions/GuildPermissions.cs#L14

The `All` value should instead be `0b11111_1111110_1111111110011_111111`.

A temporary workaround for this is to disable `Administrator` and enable this permission explicitly.
